# Generated by Django 6.1.1 on 2026-10-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_region_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.tipoinmueble'),
        ),
    ]
